name: CI

on:
  push:
    branches:
      - main
      - v0.*.x
    tags:
      - "v*"
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest hypothesis
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload pytest results to codecov
      uses: codecov/codecov-action@v1
      with:
        name: pytest-results-${{ matrix.python-version }}
        token: ${{ secrets.CODECOV_TOKEN }}
        if: always()
        files: ./coverage.xml,./coverage1.xml,./coverage2.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
